import turtle
for i in range(4):
    turtle.forward(100)
    turtle.left(90)
turtle.penup()
turtle.forward(33.3)
turtle.left(90)
turtle.forward(25)
turtle.dot("blue")
turtle.forward(25)
turtle.dot("blue")
turtle.forward(25)
turtle.dot("blue")
turtle.right(90)
turtle.forward(33.3)
turtle.right(90)
turtle.dot("blue")
turtle.forward(25)
turtle.dot("blue")
turtle.forward(25)
turtle.dot("blue")
